name: flutte_scanner_empty
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  camera: ^0.10.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_tabler_icons: ^1.43.0
  fluttertoast: ^8.2.12
  google_fonts: ^6.2.1
  http: ^1.4.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  loading_indicator: ^3.1.1
  overlay_loading_progress: ^1.0.2
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  supabase_flutter: ^2.9.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logoartero.png
    - assets/icon/logoartero(pequenyo).png
    - assets/icon/logoartero2.png
    - assets/icon/logoartero3.png
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/interItalicVariable.ttf
        - asset: assets/fonts/interVariableFont.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/logoartero.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/logoartero3.png
  android: true
  ios: true
  web: false
