name: flutte_scanner_empty
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  provider: ^6.1.4
  supabase_flutter: ^2.8.4
  google_fonts: ^6.2.1
  flutter_tabler_icons: ^1.43.0
  fluttertoast: ^8.2.12
  overlay_loading_progress: ^1.0.2
  loading_indicator: ^3.1.1
  http: ^1.3.0
  camera: ^0.11.1
  path_provider: ^2.1.5
  path: ^1.9.1
  image_picker: ^1.1.2
  # material_color_utilities: ^0.12.0 --- Incompatible actualmente

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
#  async: ^2.13.0 --- Incompatible actualmente
#  fake_async: ^1.3.3 --- Incompatible actualmente
#  leak_tracker: ^10.0.9 --- Incompatible actualmente 
#  vm_service: ^15.0.0 --- Incompatible actualmente

flutter:
  uses-material-design: true
  assets:
    - assets/icon/logoartero.png
    - assets/icon/logoartero(pequenyo).png
    - assets/icon/logoartero2.png
    - assets/icon/logoartero3.png
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/interItalicVariable.ttf
        - asset: assets/fonts/interVariableFont.ttf


flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/icon/logoartero.png" 