// Generated by Scaffolding ts
// An app developed by Brainglab, Website: https://brainglab.com

import 'dart:convert';

class GastoModel {
  String? mIdx;
  double? mGastoModelImport;
  String? mGastoModelClient;
  String? mGastoModelDescription;
  DateTime? mCreatedAt;
  DateTime? mUpdatedAt;
  String? mImageUrl;
  String? mImageId;

  GastoModel({
    String? mIdx,
    double? mGastoModelImport,
    String? mGastoModelClient,
    String? mGastoModelDescription,
    dynamic mCreatedAt,
    dynamic mUpdatedAt,
    String? mImageUrl,
    String? mImageId,
  });

  GastoModel.fromJsonMap(Map<String, dynamic> json) {
    mIdx = json['idx'];
    mGastoModelImport = json['import'];
    mGastoModelClient = json['client'];
    mGastoModelDescription = json['description'];
    mCreatedAt =
        json['created_at'] == null ? null : DateTime.parse(json['created_at']);
    mUpdatedAt =
        json['updated_at'] == null ? null : DateTime.parse(json['updated_at']);
    mImageUrl = json['imageUrl'];
    mImageId = json['imageId'];
  }

  String toJson() {
    return jsonEncode(_toJsonMap());
  }

  Map<String, dynamic> _toJsonMap() => {
    'idx': mIdx,
    'import': mGastoModelImport,
    'client': mGastoModelClient,
    'description': mGastoModelDescription,
    'created_at': mCreatedAt,
    'updated_at': mUpdatedAt,
    'imageUrl': mImageUrl,
    'imageId': mImageId,
  };
}
