// Generated by Scaffolding ts
// An app developed by Brainglab, Website: https://brainglab.com

import 'dart:convert';

class GastoModel {
  String? mIdx;
  double? mGastosModelImport;
  String? mGastosModelClient;
  String? mGastosModelDescription;
  DateTime? mCreatedAt;
  DateTime? mUpdatedAt;
  String? mImageUrl;

  GastoModel({
    mIdx,
    mGastosModelImport,
    mGastosModelClient,
    mGastosModelDescription,
    mCreatedAt,
    mUpdatedAt,
    mImageUrl,
  });

  GastoModel.fromJsonMap(Map<String, dynamic> json) {
    mIdx = json['idx'];
    mGastosModelImport = json['import'];
    mGastosModelClient = json['client'];
    mGastosModelDescription = json['description'];
    mCreatedAt =
        json['created_at'] == null ? null : DateTime.parse(json['created_at']);
    mUpdatedAt =
        json['updated_at'] == null ? null : DateTime.parse(json['updated_at']);
    mImageUrl = json['imageUrl'];
  }

  String toJson() {
    return jsonEncode(_toJsonMap());
  }

  Map<String, dynamic> _toJsonMap() => {
    'idx': mIdx,
    'import': mGastosModelImport,
    'client': mGastosModelClient,
    'description': mGastosModelDescription,
    'created_at': mCreatedAt,
    'updated_at': mUpdatedAt,
    'imageUrl': mImageUrl,
  };
}
