// Generated by Scaffolding ts
// An app developed by Brainglab, Website: https://brainglab.com

import 'dart:convert';

class TicketModel {
  String? mIdx;
  double? mTicketModelImport;
  String? mTicketModelClient;
  String? mTicketModelDescription;
  DateTime? mCreatedAt;
  DateTime? mUpdatedAt;
  String? mImageUrl;

  TicketModel({
    mIdx,
    mTicketModelImport,
    mTicketModelClient,
    mTicketModelDescription,
    mCreatedAt,
    mUpdatedAt,
    mImageUrl,
  });

  TicketModel.fromJsonMap(Map<String, dynamic> json) {
    mIdx = json['idx'];
    mTicketModelImport = json['import'];
    mTicketModelClient = json['client'];
    mTicketModelDescription = json['description'];
    mCreatedAt = json['created_at'] == null ? null : DateTime.parse(json['created_at']);
    mUpdatedAt = json['updated_at'] == null ? null : DateTime.parse(json['updated_at']);
    mImageUrl = json['imageUrl'];
  }

  String toJson() {
    return jsonEncode(_toJsonMap());
  }

  Map<String, dynamic> _toJsonMap() => {
    'idx': mIdx,
    'import': mTicketModelImport,
    'client': mTicketModelClient,
    'description': mTicketModelDescription,
    'created_at': mCreatedAt,
    'updated_at': mUpdatedAt,
    'imageUrl' : mImageUrl,
  };
}
