// Generated by Scaffolding ts
// An app developed by Brainglab, Website: https://brainglab.com

import 'dart:convert';

class Tickets {
  List<TicketModel> items = [];

  Tickets();

  Tickets.fromJsonList(List<dynamic>? jsonList) {
    if (jsonList == null) {
      return;
    } else {
      for (var item in jsonList) {
        final mTicketModel = TicketModel.fromJsonMap(item);
        items.add(mTicketModel);
      }
    }
  }

  String toArrayJson() {
    String jsonArray = '';
    for (var i = 0; i < items.length; i++) {
      jsonArray += items[i].toJson();

      if ((i + 1) < items.length) {
        jsonArray += ", ";
      }
    }

    return jsonArray = '[$jsonArray]';
  }
}

class TicketModel {
  String? mIdx;
  String? mTicketModelName;
  String? mTicketModelCodeLetter;
  String? mTicketModelCode;
  String? mTicketModelFlagUrl;
  DateTime? mCreatedAt;
  DateTime? mUpdatedAt;

  TicketModel({
    mIdx,
    mTicketModelName,
    mTicketModelCodeLetter,
    mTicketModelCode,
    mTicketModelFlagUrl,
    mCreatedAt,
    mUpdatedAt,
  });

  TicketModel.fromJsonMap(Map<String, dynamic> json) {
    mIdx = json['idx'];
    mTicketModelName = json['country_name'];
    mTicketModelCodeLetter = json['country_code_letter'];
    mTicketModelCode = json['country_code'];
    mTicketModelFlagUrl = json['country_flag_url'];
    mCreatedAt = json['created_at'] == null ? null : DateTime.parse(json['created_at']);
    mUpdatedAt = json['updated_at'] == null ? null : DateTime.parse(json['updated_at']);
  }

  String toJson() {
    return jsonEncode(_toJsonMap());
  }

  Map<String, dynamic> _toJsonMap() => {
    'idx': mIdx,
    'country_name': mTicketModelName,
    'country_code_letter': mTicketModelCodeLetter,
    'country_code': mTicketModelCode,
    'country_flag_url': mTicketModelFlagUrl,
    'created_at': mCreatedAt,
    'updated_at': mUpdatedAt,
  };
}
