// Generated by Scaffolding ts
// An app developed by Brainglab, Website: https://brainglab.com

import 'dart:convert';

class Tickets {
  List<TicketModel> items = [];

  Tickets();

  Tickets.fromJsonList(List<dynamic>? jsonList) {
    if (jsonList == null) {
      return;
    } else {
      for (var item in jsonList) {
        final mTicketModel = TicketModel.fromJsonMap(item);
        items.add(mTicketModel);
      }
    }
  }

  String toArrayJson() {
    String jsonArray = '';
    for (var i = 0; i < items.length; i++) {
      jsonArray += items[i].toJson();

      if ((i + 1) < items.length) {
        jsonArray += ", ";
      }
    }

    return jsonArray = '[$jsonArray]';
  }
}

class TicketModel {
  String? mIdx;
  String? mTicketModelImport;
  String? mTicketModelClient;
  String? mTicketModelDescription;
  DateTime? mCreatedAt;
  DateTime? mUpdatedAt;

  TicketModel({
    mIdx,
    mTicketModelImport,
    mTicketModelClient,
    mTicketModelDescription,
    mCreatedAt,
    mUpdatedAt,
  });

  TicketModel.fromJsonMap(Map<String, dynamic> json) {
    mIdx = json['idx'];
    mTicketModelImport = json['import'];
    mTicketModelClient = json['client'];
    mTicketModelDescription = json['description'];
    mCreatedAt = json['created_at'] == null ? null : DateTime.parse(json['created_at']);
    mUpdatedAt = json['updated_at'] == null ? null : DateTime.parse(json['updated_at']);
  }

  String toJson() {
    return jsonEncode(_toJsonMap());
  }

  Map<String, dynamic> _toJsonMap() => {
    'idx': mIdx,
    'import': mTicketModelImport,
    'client': mTicketModelClient,
    'description': mTicketModelDescription,
    'created_at': mCreatedAt,
    'updated_at': mUpdatedAt,
  };
}
